# Generated by Django 5.1.3 on 2024-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerOnOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Стоимость товара",
                        max_length=255,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(
                        help_text="Срок поставки",
                        max_length=255,
                        verbose_name="Срок поставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amounts",
                    models.CharField(
                        help_text="Количество товара в заявке",
                        max_length=50,
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заявке",
                "verbose_name_plural": "Товары в заявке",
            },
        ),
        migrations.CreateModel(
            name="PriceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ цен",
                "verbose_name_plural": "Анализы цен",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=255,
                        verbose_name="Товар",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        help_text="Артикул товара",
                        max_length=255,
                        null=True,
                        verbose_name="Артикул",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
