# Generated by Django 5.1.3 on 2024-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(
                blank=True,
                help_text="Артикул товара, должен быть уникальным",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Название товара, обязательное поле",
                max_length=255,
                verbose_name="Товар",
            ),
        ),
    ]
