# Generated by Django 5.1.3 on 2024-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0003_alter_orderproduct_order_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="measurement",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Единица измерения"
            ),
        ),
    ]
