# Generated by Django 5.1.3 on 2024-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0004_product_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="amounts",
            field=models.CharField(
                blank=True,
                help_text="Количество товара в заявке",
                max_length=50,
                null=True,
                verbose_name="Количество",
            ),
        ),
    ]
