# Generated by Django 5.1.3 on 2024-12-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0004_alter_answeronorder_delivery_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
