# Generated by Django 5.1.3 on 2024-12-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0005_remove_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(
                help_text="Товары в заявке",
                related_name="order_products",
                through="tender.OrderProduct",
                to="tender.product",
            ),
        ),
    ]
