# Generated by Django 5.1.3 on 2024-11-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0005_alter_orderproduct_amounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="amounts",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Количество товара в заявке",
                max_digits=10,
                null=True,
                verbose_name="Количество",
            ),
        ),
    ]
