# Generated by Django 5.1.3 on 2024-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0006_alter_orderproduct_amounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeronorder",
            name="delivery_time",
            field=models.CharField(
                default=None,
                help_text="Срок поставки",
                max_length=255,
                verbose_name="Срок поставки",
            ),
        ),
        migrations.AlterField(
            model_name="answeronorder",
            name="price",
            field=models.CharField(
                default=0,
                help_text="Стоимость товара",
                max_length=255,
                verbose_name="Цена",
            ),
        ),
    ]
