# Generated by Django 5.1.3 on 2024-12-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0006_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(
                blank=True,
                help_text="Артикул товара, должен быть уникальным",
                max_length=255,
                null=True,
                verbose_name="Артикул",
            ),
        ),
    ]
