# Generated by Django 5.1.3 on 2024-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0007_alter_product_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Пропишите краткое описание о товарах в заявке",
                max_length=255,
                null=True,
                verbose_name="Краткое описание заявки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="number_ERP",
            field=models.CharField(
                blank=True,
                help_text="Номер заказа из 1С, не обязательное поле",
                max_length=15,
                null=True,
                verbose_name="Номер заказа из 1С",
            ),
        ),
    ]
