# Generated by Django 5.1.3 on 2024-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0008_order_description_order_number_erp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="duration",
            field=models.DateField(
                blank=True,
                help_text="Крайняя дата получения ответов на заявку",
                null=True,
                verbose_name="Срок ответа",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Актуальна ли ещё заявка?",
                verbose_name="Актуальная заявка",
            ),
        ),
    ]
