# Generated by Django 5.1.3 on 2024-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0009_order_duration_order_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="duration",
            field=models.DateField(
                blank=True,
                help_text="Крайняя дата получения ответов на заявку, формат ДД.ММ.ГГГГ",
                null=True,
                verbose_name="Срок ответа",
            ),
        ),
    ]
