# Generated by Django 5.1.3 on 2024-12-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0010_alter_order_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeronorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Стоимость товара (в рублях, с НДС).",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
